### ISSUE TITLE
SSL error on loading the adapter

### ISSUE THREAD

**Issue by sghose-ttc** [unixcharles/hubot-talker#12]
Getting the following error when loading the adapter in Linux Mint (Nadia). Chrome shows cert for talkerapp.com as valid, expiring on Oct 2013.

```
{ host: 'talkerapp.com',
  encoding: 'utf8',
  port: 8500,
  sockets: {} }
[Thu May 16 2013 02:13:04 GMT-0700 (PDT)] INFO /home/sudipta/sghubot/scripts/pugme.coffee is using deprecated documentation syntax

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: CERT_HAS_EXPIRED
  at SecurePair.<anonymous> (tls.js:1283:32)
  at SecurePair.EventEmitter.emit (events.js:92:17)
  at SecurePair.maybeInitFinished (tls.js:896:10)
  at CleartextStream.read [as _read] (tls.js:430:15)
  at CleartextStream.Readable.read (_stream_readable.js:304:10)
  at EncryptedStream.write [as _write] (tls.js:344:25)
  at doWrite (_stream_writable.js:211:10)
  at writeOrBuffer (_stream_writable.js:201:5)
  at EncryptedStream.Writable.write (_stream_writable.js:172:11)
  at write (_stream_readable.js:557:24)
  at flow (_stream_readable.js:566:7)
  at Socket.pipeOnReadable (_stream_readable.js:598:5)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:392:10)
  at emitReadable (_stream_readable.js:388:5)
  at readableAddChunk (_stream_readable.js:150:9)
  at Socket.Readable.push (_stream_readable.js:113:10)
  at TCP.onread (net.js:511:21)

 Can load it by changing tls.connect to net.connect. But it can't send anything and gets this error
Disconnected (reason: cannot send with readyState: closed)
```

**Comment by unixcharles** [comment]
hmm, not sure what it is, I was no able to reproduce locally.

It might be an environment problem, anyone else is having this problem?

I know that for sure that our certificate valid

**Comment by jenshaase** [comment]
Hi,

I also got this problem. The talkerapp certificate on port 8500 is not valid. It has expired at 10/26/2012.

Cheers,
Jens

**Comment by sghose-ttc** [comment]
I am using a workaround for now passing rejectUnauthorized: false in the tls.connect call.

**Comment by unixcharles** [comment]
Hey @magec do you know anything about that?

**Comment by magec** [comment]
Changed the cert file, @sghose-ttc now its ok. Sorry for the inconvenience.

**Comment by unixcharles** [comment]
thanks @magec!

**Comment by sghose-ttc** [comment]
Just tested it. Works great! Thanks @magec and @unixcharles for resolving this quickly.

**Comment by unixcharles** [comment]
No problem, thanks for letting us know.
