### ISSUE TITLE
"cannot load adapter"

### ISSUE THREAD

**Issue by webdesserts** [unixcharles/hubot-talker#9]
I've been getting this error while trying to deploy my hubot to heroku:

```
[Tue Jul 31 2012 23:34:48 GMT+0000 (UTC)] ERROR Cannot load adapter talker - TypeError: Cannot read property 'prototype' of undefined
2012-07-31T23:34:48+00:00 app[web.1]: TypeError: Cannot call method 'on' of null
2012-07-31T23:34:48+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:105:19)
2012-07-31T23:34:48+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:109:4)
2012-07-31T23:34:48+00:00 app[web.1]:     at Module._compile (module.js:446:26)
2012-07-31T23:34:48+00:00 app[web.1]:     at Object.run (/app/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:79:25)
2012-07-31T23:34:48+00:00 app[web.1]:     at /app/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/command.js:177:29
2012-07-31T23:34:48+00:00 app[web.1]:     at /app/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/command.js:152:18
2012-07-31T23:34:48+00:00 app[web.1]:     at [object Object].<anonymous> (fs.js:123:5)
2012-07-31T23:34:48+00:00 app[web.1]:     at [object Object].emit (events.js:64:17)
2012-07-31T23:34:48+00:00 app[web.1]:     at Object.oncomplete (fs.js:1190:12)
2012-07-31T23:34:49+00:00 heroku[web.1]: Process exited with status 1
2012-07-31T23:34:49+00:00 heroku[web.1]: State changed from starting to crashed
```

Any ideas on what the issue might be? I have all my keys, Procfile, and dependencies set correctly to my knowledge.

**Comment by webdesserts** [comment]
Fixed it on my end. I updated hubot to 2.3.2
The version downloadable on [hubot's site](http://hubot.github.com/) is 2.2.0

Was the adapter still supposed to be backwards compatible?
